services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: websearch
      POSTGRES_PASSWORD: webpass
      POSTGRES_USER: webuser
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend/app
    volumes:
      - ./backend/app:/app
      - ./frontend:/app/frontend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://webuser:webpass@db:5432/websearch

volumes:
  pgdata: