"""delete 2 tables

Revision ID: 7d6902e0eb9b
Revises: 9d8d2bbe554b
Create Date: 2025-09-19 14:50:45.203457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d6902e0eb9b'
down_revision: Union[str, Sequence[str], None] = '9d8d2bbe554b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_videos_id'), table_name='job_videos')
    op.drop_table('job_videos')
    op.drop_index(op.f('ix_profession_media_id'), table_name='profession_media')
    op.drop_table('profession_media')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profession_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('profession_media_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profession_media_pkey'))
    )
    op.create_index(op.f('ix_profession_media_id'), 'profession_media', ['id'], unique=False)
    op.create_table('job_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('job_videos_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_videos_pkey'))
    )
    op.create_index(op.f('ix_job_videos_id'), 'job_videos', ['id'], unique=False)
    # ### end Alembic commands ###
