"""Add job photos and videos tables

Revision ID: 9d8d2bbe554b
Revises: 001_initial_schema
Create Date: 2025-09-14 15:17:25.792968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8d2bbe554b'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_photos_id'), 'job_photos', ['id'], unique=False)
    op.create_table('job_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_videos_id'), 'job_videos', ['id'], unique=False)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_job_videos_id'), table_name='job_videos')
    op.drop_table('job_videos')
    op.drop_index(op.f('ix_job_photos_id'), table_name='job_photos')
    op.drop_table('job_photos')
    # ### end Alembic commands ###
