"""add cascade delete to JobsTable

Revision ID: ad9ca90953c1
Revises: 7d6902e0eb9b
Create Date: 2025-09-22 15:25:25.493896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9ca90953c1'
down_revision: Union[str, Sequence[str], None] = '7d6902e0eb9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
